# Generated by Django 5.1.2 on 2025-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_dependencia_inicio_consecutivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo_correspondencia',
            field=models.CharField(choices=[('Carta', 'Carta'), ('Memorando', 'Memorando'), ('Email', 'Email'), ('DP', 'DP'), ('Cotizacion', 'Cotizacion')], max_length=20),
        ),
    ]
